/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Logo3d/logo3d.gltf -t -r public 
*/

import * as THREE from 'three'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Box: THREE.Mesh
    Box_1: THREE.Mesh
  }
  materials: {
    ['Titanium Glossy']: THREE.MeshStandardMaterial
    ['Titanium Glossy 1']: THREE.MeshStandardMaterial
  }
}

export function Logo3D(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Logo3d/logo3d.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.001, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={30}>
        <mesh geometry={nodes.Box.geometry} material={materials['Titanium Glossy']} position={[32.75, 0, 31.774]} rotation={[0, -Math.PI / 4, 0]} scale={[0.926, 0.1, 0.926]} />
        <mesh geometry={nodes.Box_1.geometry} material={materials['Titanium Glossy 1']} position={[-32.75, 0, 90.562]} rotation={[0, Math.PI / 4, 0]} scale={[0.926, 0.1, 0.926]} />
      </group>
      <spotLight intensity={0.4} angle={Math.PI / 4} penumbra={0.15} decay={2} distance={10000} position={[0.163, 0.341, -0.244]} rotation={[-2.273, 0.353, 0.277]} scale={0.001} />
      <PerspectiveCamera makeDefault={false} far={66.745} near={0.014} fov={35} position={[-0.414, 0.209, -1.18]} rotation={[-3.083, -0.36, -3.121]} />
    </group>
  )
}

useGLTF.preload('/Logo3d/logo3d.gltf')
